version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - gear-track-network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=geartrack
      - DB_PASSWORD=geartrackpass
      - DB_NAME=geartrack
      - CORS_ORIGINS=http://localhost:3000
    networks:
      - gear-track-network
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: GearTrack
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bankpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - gear_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  gear_data:

networks:
  gear-track-network:
    driver: bridge