version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: GearTrack
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bankpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - gear_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  gear_data: