apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: webservice
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webservice
      tier: frontend
  template:
    metadata:
      labels:
        app: webservice
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/frontend:latest # Replace with your Docker Hub image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: webservice
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: webservice
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webservice
      tier: backend
  template:
    metadata:
      labels:
        app: webservice
        tier: backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/backend:latest # Replace with your Docker Hub image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: webservice
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP